import UIKit

struct StringConstants {
    static let kLblContinue: String = "Continue"
    static let k: String = ""
    static let kMsgInvestmentRepo: String = "Investment Report"
    static let kMsgStatementOfCh: String = "Statement of Changes"
    static let kLblResend: String = "Resend"
    static let kLblResetPassword: String = "Reset Password"
    static let kLblImportantNotes: String = "Important Notes"
    static let kLblReporting: String = "Reporting"
    static let kMsgSelectInstitut2: String = "Select institution code..."
    static let kLblAuditReport: String = "Audit Report"
    static let kMsgInstitutionCod: String = "Institution Code "
    static let kLblAppNavigation: String = "App Navigation"
    static let kLblPortfolio: String = "Portfolio"
    static let kMsgSelectPortfoli: String = "Select portfolio..."
    static let kMsgExistingClient: String = "Existing clients \nplease log-in below."
    static let kMsgReportingSecti: String = "Reporting Section"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kMsgYouHaveNotRe: String = "You have not received the email?  Resend"
    static let kLblSuccessfully: String = "Successfully"
    static let kMsgForgotPassword: String = "Forgot Password?"
    static let kMsgNonMarketable: String = "Non Marketable Account Summary"
    static let kLblBackToLogin2: String = "Back to login"
    static let kMsgHelloJohnSmit: String = "Hello John Smith."
    static let kLblUsername: String = "Username"
    static let kMsgTheNextAvaila: String =
        "The next available month end transatcion date is June xx,\n2022 with notification on or before June xx, 2022. Please\ncontact Investor Services 888-823-3863 with any\ntransaction related questions. "
    static let kMsgImportantNotif: String = "Important Notification"
    static let kMsgSelectInstitut: String = "Select institution..."
    static let kLblEmail: String = "Email "
    static let kLblResetPassword2: String = "Reset password"
    static let kMsgCheckYourEmai: String = "Check Your Email"
    static let kMsgWeHaveSentTh: String =
        "We have sent the reset password to the email address johnsmith@outlook.com"
    static let kMsgCapitalCallDi: String = "Capital Call Distributions"
    static let kMsgPartnershipLif: String = "Partnership Lifestyle Report"
    static let kLblBackToLogin: String = "Back to Login"
    static let kLblLogo: String = "Logo"
    static let kLblLogin: String = "Login"
    static let kLblSecureAccess: String = "Secure Access "
    static let kMsgYouHaveNotRe2: String = "You have not received the email?  "
    static let kMsgDonTShowMeT: String = "Don’t show me this alert again"
    static let kLblBatchReporting: String = "Batch Reporting "
    static let kMsgNotificationEx: String = "Notification Example"
    static let kMsgYourPasswordH: String =
        "Your password has been updated, please change your password regularly to avoid this happening"
    static let kMsgCostAccounting: String = "Cost Accounting Report"
    static let kHttpFail: String = "HTTP request failed"
    static let kMsgCostAndMarket: String = "Cost and Market Value"
    static let kLblForgotPassword: String = "Forgot Password"
    static let kMsgImportantInfor: String = "Important Information"
    static let kLblOk: String = "Ok"
    static let kMsgMonthEndProce: String = "Month End Processing Update"
    static let kMsgCheckYourApp: String =
        "Check your app's UI from the below demo screens of your app."
    static let kLblPassword: String = "Password"
    static let kLblApplyNow: String = "Apply Now"
    static let kMsgFinalMayXx2: String =
        "Final May xx, 2022 positions for marketable investments\nand performance are now available. Detailed strategy\nallocations for Multi-Strategy and Global Multi-Asset \nFunds are now updated, as of June xx.\n\nEffect March xx, 2022, the Passive Index Strategy will\nbe included in the Non-US Strategy performance.  "
    static let kLblHomeScreen: String = "Home Screen"
    static let kMsgByLoggingInA: String =
        "By logging in and using the account information of this Website, you agree that Commonfund will have no liability for damages arising from any actions such as investment decisions, taken by or \nor behalf of your institution based on the accuracy of \nthe account data presented in this app. "
    static let kInvalidUrl: String = "Invalid URL"
    static let kLblInstitution: String = "Institution "
    static let kMsgMarketableAcco: String = "Marketable Account Summary"
    static let kLblRememberMe: String = "Remember me?"
}
