VStack(spacing: 24.33) {
    Text("Successfully")
    .fontWeight(.bold)
    .font(.largeTitle)

    Text("Your password has been updated, please change your password regularly to avoid this happening")
    .font(.caption)
    .multilineTextAlignment(.center)
    .frame(width: 305, alignment: .top)
    .lineSpacing(19.20)

    Text("CONTINUE")
    .fontWeight(.bold)
    .font(.subheadline)
    .frame(width: 83, alignment: .topLeading)
    .tracking(0.84)
    .padding(.horizontal, 117)
    .padding(.top, 17)
    .padding(.bottom, 15)
    .frame(width: 317, height: 50)
    .background(Color(red: 0.07, green: 0, blue: 0.38))
    .cornerRadius(6)
    .shadow(radius: 62, y: 4)
    .frame(width: 317, height: 50)

    Text("BACK TO LOGIN")
    .fontWeight(.bold)
    .font(.subheadline)
    .frame(width: 122, alignment: .topLeading)
    .tracking(0.84)
    .padding(.leading, 98)
    .padding(.trailing, 97)
    .padding(.top, 17)
    .padding(.bottom, 15)
    .frame(width: 317, height: 50)
    .background(Color(red: 0.84, green: 0.80, blue: 1))
    .cornerRadius(6)
    .frame(width: 317, height: 50)
}
.padding(.leading, 25)
.padding(.trailing, 29)
.padding(.top, 295)
.padding(.bottom, 243)
.frame(width: 375, height: 812)
.background(Color(red: 0.95, green: 0.95, blue: 0.95))
.cornerRadius(30)